server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scooter_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-app.sql
      data-locations:
        - classpath:seed-app.sql
        - classpath:seed-users.sql
        - classpath:seed-demo-data.sql
      continue-on-error: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
